easy_admin:
    site_name: Mindful beauty
    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { entity: 'Article', label: 'Article', icon: 'map-marker' }
            - { entity: 'Comment', label: 'Comments', icon: 'comments' }

    entities:
        Article:
            class: App\Entity\Article

        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - state
                    - { property: 'createdAt', type: 'datetime' }
                sort: ['createdAt', 'ASC']
                filters: ['article']
            edit:
                fields:
                    - { property: 'article' }
                    - { property: 'createdAt', type: datetime, type_options: { disabled: true } }
                    - 'author'
                    - {property: 'state'}
                    - { property: 'email', type: 'email' }
                    - text
