version: '3'

services:
    
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: mbeauty
            POSTGRES_PASSWORD: mbeauty
            POSTGRES_DB: mbeauty
        ports: [5432]
    
    
    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]